server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html index.htm;

  location /create {
    proxy_pass http://backend:5000/create;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /guess {
    proxy_pass http://backend:5000/guess;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /health {
    proxy_pass http://backend:5000/health;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
